version: "3.8"

services:
  restaurant-service:
    build: ./services/restaurant-service
    ports:
      - "3001:3000"

  payment-service:
    build: ./services/payment-service
    ports:
      - "3003:3000"

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3000"
    environment:
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3000
      - PAYMENT_SERVICE_URL=http://payment-service:3000
    depends_on:
      - restaurant-service
      - payment-service